### PR TITLE
Remove cifra dir; add missing assert.h

### PR DESCRIPTION
**Pull request by smittytone**
Fixes for build issues: assert.h errors, cifra submodule errors. 

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [X] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

**Comment by smittytone** [comment]
NOTE Builds on macOS native, Ubuntu 20.0.4 using main's deploy.sh

**Review by rbeiter — CHANGES_REQUESTED** [review]
Just one change needed - since we are now using the updated deploy.sh, we need to drop the specific version tag in the Dockerfile for the CLI or the docker build path fails.

```
diff --git a/Dockerfile b/Dockerfile
index 4a19db9..4a25b1c 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -25,6 +25,6 @@ WORKDIR /home/${USERNAME}/
 USER $USERNAME

 RUN twilio update \
-  && twilio plugins:install "@twilio/plugin-microvisor@0.3.7"
+  && twilio plugins:install "@twilio/plugin-microvisor"

 ENTRYPOINT ./project/docker-entrypoint.sh
```

**Review by rbeiter — APPROVED** [review]
This looks good to me, merging and updating the README to reflect direct support for Apple Silicon that's in the PR as well.

**Review by rbeiter — CHANGES_REQUESTED** [review]
Review the other PR, I think it will merge cleaner and has all outstanding changes reflected.

**Pull request closed without merging**
